### ISSUE TITLE
IE 11 (💩) tables display issue(?)

### ISSUE THREAD

**Issue by equinusocio** [contactlab/contactlab-ui-components#108]
**Responsive Table** and **Full Table**  don't work on IE 11 Windows 8.1 (It's a problem?)

![screen shot 2017-01-27 at 16 03 07](https://cloud.githubusercontent.com/assets/10454741/22375442/57ca8126-e4aa-11e6-90f7-74644d392322.png)

**Comment by equinusocio** [comment]
Probably this will be a refactor because of code complexity and maintainability

**Comment by equinusocio** [comment]
```css
.responsive-table {
  display: flex;
  flex-direction: column;
}

.table .thead {
  display: flex;
  flex-basis: 100%;
}

.tbody {
  display: flex;
  flex-flow: column nowrap;
}

.responsive-table .tr {
  display: flex;
  flex: 1;
}


.responsive-table .td,
.responsive-table .th {
  flex-basis: 100%;
}
```
