### ISSUE TITLE
<dropdown-clab> placeholder

### ISSUE THREAD

**Issue by Arual90** [contactlab/contactlab-ui-components#114]
The placeholder and the selected option styles look the same.

Placeholder:
![schermata 2017-02-13 alle 10 16 07](https://cloud.githubusercontent.com/assets/6952430/22877374/7847d2c2-f1d5-11e6-9c60-e9041813ac04.png)

Option:
![schermata 2017-02-13 alle 10 16 15](https://cloud.githubusercontent.com/assets/6952430/22877379/7c995742-f1d5-11e6-9f91-40737c345821.png)

It is confusing, it would be better if the placeholder text had a distinguishing style

**Comment by equinusocio** [comment]
If he uses the html `placeholder` attribute we can use this snippet:

```css
::-webkit-input-placeholder { /* Chrome/Opera/Safari */
  color: pink;
}
::-moz-placeholder { /* Firefox 19+ */
  color: pink;
}
:-ms-input-placeholder { /* IE 10+ */
  color: pink;
}
:-moz-placeholder { /* Firefox 18- */
  color: pink;
}
```
