### ISSUE TITLE
Sanitize some components styles

### ISSUE THREAD

**Issue by giotramu** [contactlab/contactlab-ui-components#228]
Apply the following style resets:

- **General:**

    ```css
    ol,
    ul {
      padding: 0;
    }
    ```

- **Form:**
 
    ```css
    label {
      color: var(--color-base800);
    
      &[disabled] {
        color: var(--color-base500);
      }
    }
    ```
    
    ```css
    .key-value li span:first-of-type {
      color: var(--color-base800);
    
      &[disabled] {
        color: var(--color-base500);
      }
    }
    ```

- **Accordion:**

    ```css
    .accordion-block {
      padding: 0;
    
      &.active {
        margin: 0;
      }
    }
    ```
